/*
 * Licensed to CRATE Technology GmbH ("Crate") under one or more contributor
 * license agreements.  See the NOTICE file distributed with this work for
 * additional information regarding copyright ownership.  Crate licenses
 * this file to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.  You may
 * obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations
 * under the License.
 *
 * However, if you have executed another commercial license agreement
 * with Crate these terms will supersede the license and you may use the
 * software solely pursuant to the terms of the relevant commercial agreement.
 */

package io.crate.analyze;

import com.google.common.base.Preconditions;
import io.crate.core.StringUtils;
import io.crate.core.collections.StringObjectMaps;
import io.crate.exceptions.CrateException;
import io.crate.exceptions.ValidationException;
import io.crate.metadata.ReferenceIdent;
import io.crate.metadata.ReferenceInfo;
import io.crate.metadata.TableIdent;
import io.crate.planner.symbol.Reference;
import io.crate.planner.symbol.Symbol;
import io.crate.sql.tree.*;
import org.apache.lucene.util.BytesRef;

import java.util.*;

public class InsertStatementAnalyzer extends DataStatementAnalyzer<InsertAnalysis> {

    @Override
    public Symbol visitInsert(Insert node, InsertAnalysis context) {
        process(node.table(), context);

        if (context.table().isAlias()) {
            throw new IllegalArgumentException("Table alias not allowed in INSERT statement.");
        }
        int maxValuesLength = node.maxValuesLength();
        if (node.columns().size() == 0) {
            if (maxValuesLength > context.table().columns().size()) {
                throw new IllegalArgumentException("too many values");
            }
            // no columns given in statement

            int i = maxValuesLength;
            context.columns(new ArrayList<Reference>(maxValuesLength));
            for (ReferenceInfo columnInfo : context.table().columns()) {
                if (i==0) { break; }

                addColumn(columnInfo.ident(), context);
                i--;
            }

        } else {
            if (maxValuesLength > node.columns().size()) {
                throw new IllegalArgumentException("too many values");
            }
            context.columns(new ArrayList<Reference>(node.columns().size()));
            for (String column : node.columns()) {
                addColumn(column, context);
            }
        }

        context.allocateValues(node.valuesLists().size());


        if (!context.table().hasAutoGeneratedPrimaryKey() && context.primaryKeyColumnIndices().size() == 0) {
            throw new IllegalArgumentException("Primary key is required but is missing from the insert statement");
        }

        if (context.table().clusteredBy() != null
                && !context.table().clusteredBy().equalsIgnoreCase("_id")
                && context.routingColumnIndex() < 0) {
            throw new IllegalArgumentException("Clustered by value is required " +
                    "but is missing from the insert statement");
        }

        context.visitValues();
        for (ValuesList valuesList : node.valuesLists()) {
            process(valuesList, context);
        }

        return null;
    }

    private Reference addColumn(String column, InsertAnalysis context) {
        assert context.table() != null;
        return addColumn(new ReferenceIdent(context.table().ident(), column), context);
    }

    private Reference addColumn(ReferenceIdent ident, InsertAnalysis context) {
        String column = ident.columnIdent().fqn();
        Preconditions.checkArgument(!column.startsWith("_"), "Inserting system columns is not allowed");

        // set primary key index if found
        if (StringUtils.pathListContainsPrefix(context.table().primaryKey(), column)) {
            context.addPrimaryKeyColumnIdx(context.columns().size());
        }

        // set routing if found
        String routing = context.table().clusteredBy();
        if (routing != null && StringUtils.pathListContainsPrefix(Arrays.asList(routing), column)) {
            context.routingColumnIndex(context.columns().size());
        }

        // ensure that every column is only listed once
        Reference columnReference = context.allocateUniqueReference(ident);
        context.columns().add(columnReference);
        return columnReference;
    }

    @Override
    protected Symbol visitTable(Table node, InsertAnalysis context) {
        Preconditions.checkState(context.table() == null, "inserting into multiple tables is not supported");
        context.editableTable(TableIdent.of(node));
        return null;
    }

    /**
     * visit columns, if given in statement
     */
    @Override
    protected Symbol visitQualifiedNameReference(QualifiedNameReference node, InsertAnalysis context) {
        if (context.isVisitingValues()) {
            // column references not allowed in values, throw an error here
            throw new CrateException("column references not allowed in insert values.");
        }

        return addColumn(context.getReference(node.getName()), context);
    }

    @Override
    public Symbol visitValuesList(ValuesList node, InsertAnalysis context) {
        List<Symbol> symbols = new ArrayList<>();

        Map<String, Object> sourceMap = new HashMap<>(node.values().size());
        List<String> primaryKeyValues = new ArrayList<>();
        String routingValue = null;

        int i = 0;
        if (node.values().size() != context.columns().size()) {
            throw new IllegalArgumentException("incorrect number of values");
        }
        for (Expression expression : node.values()) {
            // TODO: instead of doing a type guessing and then a conversion this could
            // be improved by using the dataType from the column Reference as a hint
            Symbol valuesSymbol = process(expression, context);

            // implicit type conversion
            Reference column = context.columns().get(i);
            try {
                valuesSymbol = context.normalizeInputForReference(valuesSymbol, column);
            } catch (IllegalArgumentException|UnsupportedOperationException e) {
                throw new ValidationException(column.info().ident().columnIdent().fqn(), e);
            }
            symbols.add(valuesSymbol);

            try {
                Object value = ((io.crate.operation.Input)valuesSymbol).value();
                if (value instanceof BytesRef) {
                    value = ((BytesRef) value).utf8ToString();
                }
                sourceMap.put(
                        column.info().ident().columnIdent().name(),
                        value
                );
                String columnName = column.info().ident().columnIdent().fqn();
                if (context.primaryKeyColumnIndices().contains(i)) {
                    int idx = context.table().primaryKey().indexOf(columnName);
                    Object pkValue = value;
                    if (idx < 0) {
                        // oh look, a nested primary key!
                        String pkColumnName = StringUtils.getPathByPrefix(context.table.primaryKey(), columnName);
                        assert value instanceof Map;
                        pkValue = StringObjectMaps.getByPath((Map<String, Object>)value, pkColumnName);
                        idx = context.table.primaryKey().indexOf(pkColumnName); // set index to correct column
                    }
                    if (pkValue == null) {
                        throw new IllegalArgumentException("Primary key value must not be NULL");
                    }

                    if (primaryKeyValues.size() > idx) {
                        primaryKeyValues.add(idx, pkValue.toString());
                    } else {
                        primaryKeyValues.add(pkValue.toString());
                    }
                }
                if (i == context.routingColumnIndex()) {
                    Object clusteredByValue = value;
                    if (!columnName.equals(context.table().clusteredBy())) {
                        // oh my gosh! A nested clustered by value!!!
                        assert value instanceof Map;
                        clusteredByValue = StringObjectMaps.getByPath((Map<String, Object>)value, context.table().clusteredBy());
                    }
                    if (clusteredByValue == null) {
                        throw new IllegalArgumentException("Clustered by value must not be NULL");
                    }

                    routingValue = clusteredByValue.toString();
                }
            } catch (ClassCastException e) {
                // symbol is no input
                throw new CrateException(String.format("invalid value '%s' in insert statement", valuesSymbol.toString()));
            }

            i++;
        }
        context.values().add(symbols);

        context.sourceMaps().add(sourceMap);
        context.addIdAndRouting(primaryKeyValues, routingValue);

        return null;
    }
}
