# Configuration for support-requests - https://github.com/dessant/support-requests

supportLabel: support

supportComment: >
  We use the issue tracker exclusively for bug reports and feature requests.
  However, this issue appears to be a support request. Please use [Stackoverflow](https://stackoverflow.com/questions/tagged/cratedb), the [CrateDB Community Discourse](https://community.crate.io/) or consider our [enterprise support](https://crate.io/pricing/) offerings to get help with the project.

close: true
lock: false
