---
queue_rules:
  - name: default
    conditions:
      - check-success=ci/jenkins/pr_tests
      - check-success~=^Test CrateDB SQL on ubuntu
      - check-success=docs/readthedocs.org:crate
      - check-success~=^checkstyle
      - check-success~=^Vale


pull_request_rules:
  - name: automatic merge
    conditions:
      - label=ready-to-merge
      - '#approved-reviews-by>=1'
      - status-success=ci/jenkins/pr_tests
      - status-success~=^Test CrateDB SQL on ubuntu
      - status-success=docs/readthedocs.org:crate
      - status-success~=^checkstyle
      - status-success~=^Vale
    actions:
      queue:
        method: rebase
        name: default

  - name: backport 5.1
    actions:
      backport:
        ignore_conflicts: true
        branches:
          - '5.1'
    conditions:
      - label=ready-to-merge
      - label=v/5.1

  - name: backport 5.0
    actions:
      backport:
        ignore_conflicts: true
        branches:
          - '5.0'
    conditions:
      - label=ready-to-merge
      - label=v/5.0
