---
queue_rules:
  - name: default
    queue_conditions:
      - status-success=verification/cla-signed
      - status-success=ci/jenkins/pr_tests
      - status-success~=^Test CrateDB SQL on ubuntu
      - status-success=docs/readthedocs.org:crate
      - status-success~=^checkstyle
      - status-success~=^forbiddenApis
      - status-success~=^Vale
    merge_conditions:
      - label=ready-to-merge
      - '#approved-reviews-by>=1'
    merge_method: rebase

pull_request_rules:
  - name: default
    conditions: []
    actions:
      queue:
