---
rules:
  default:
    merge_strategy:
      method: rebase
      rebase_fallback: none
    enabling_label: ready-to-merge
    protection:
      required_status_checks:
        strict: true
        contexts:
          - ci/jenkins/pr_tests
          - crate.crate
          - Shippable
          - 'LGTM analysis: Java'
          - 'LGTM analysis: Python'
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: false
      enforce_admins: true
    automated_backport_labels:
      v/3.0: "3.0"
      v/3.1: "3.1"
