---
pull_request_rules:
  - actions:
      merge:
        method: rebase
        rebase_fallback: null
        strict: true
    conditions:
      - label=ready-to-merge
      - '#approved-reviews-by>=1'
      - status-success=ci/jenkins/pr_tests
      - status-success=crate.crate
      - status-success=Shippable
      - 'status-success=LGTM analysis: Java'
      - 'status-success=LGTM analysis: Python'
    name: default
  - name: Delete branch after merge
    actions:
      delete_head_branch: {}
    conditions:
      - merged
  - actions:
      backport:
        branches:
          - '3.0'
    conditions:
      - label=ready-to-merge
      - label=v/3.0
    name: backport 3.0
  - actions:
      backport:
        branches:
          - '3.1'
    conditions:
      - label=ready-to-merge
      - label=v/3.1
    name: backport 3.1
