---
queue_rules:
  - name: default
    conditions:
      - check-success=ci/jenkins/pr_tests
      - check-success~=^Test CrateDB SQL on ubuntu
      - check-success=docs/readthedocs.org:crate
      - check-success~=^checkstyle
      - check-success~=^forbiddenApis
      - check-success~=^Vale


pull_request_rules:
  - name: automatic merge
    conditions:
      - label=ready-to-merge
      - '#approved-reviews-by>=1'
      - status-success=ci/jenkins/pr_tests
      - status-success~=^Test CrateDB SQL on ubuntu
      - status-success=docs/readthedocs.org:crate
      - status-success~=^checkstyle
      - status-success~=^forbiddenApis
      - status-success~=^Vale
    actions:
      queue:
        method: rebase
        name: default

  - name: backport 5.5
    actions:
      backport:
        ignore_conflicts: true
        branches:
          - '5.5'
    conditions:
      - label=ready-to-merge
      - label=v/5.5

  - name: backport 5.4
    actions:
      backport:
        ignore_conflicts: true
        branches:
          - '5.4'
    conditions:
      - label=ready-to-merge
      - label=v/5.4

  - name: backport 5.3
    actions:
      backport:
        ignore_conflicts: true
        branches:
          - '5.3'
    conditions:
      - label=ready-to-merge
      - label=v/5.3
