---
queue_rules:
  - name: default
    queue_conditions:
      - status-success~=^check-author-signed-cla
      - status-success=ci/jenkins/pr_tests
      - status-success~=^Test CrateDB SQL on ubuntu
      - status-success=docs/readthedocs.org:crate
      - status-success~=^checkstyle
      - status-success~=^forbiddenApis
      - status-success~=^Vale
    merge_conditions:
      - label=ready-to-merge
      - '#approved-reviews-by>=1'
    merge_method: rebase

pull_request_rules:
  - name: default
    conditions: []
    actions:
      queue:

  - name: backport 5.9
    actions:
      backport:
        ignore_conflicts: true
        branches:
          - '5.9'
    conditions:
      - label=ready-to-merge
      - label=v/5.9

  - name: backport 5.8
    actions:
      backport:
        ignore_conflicts: true
        branches:
          - '5.8'
    conditions:
      - label=ready-to-merge
      - label=v/5.8

  - name: backport 5.7
    actions:
      backport:
        ignore_conflicts: true
        branches:
          - '5.7'
    conditions:
      - label=ready-to-merge
      - label=v/5.7

  - name: backport 5.6
    actions:
      backport:
        ignore_conflicts: true
        branches:
          - '5.6'
    conditions:
      - label=ready-to-merge
      - label=v/5.6

  - name: backport 5.5
    actions:
      backport:
        ignore_conflicts: true
        branches:
          - '5.5'
    conditions:
      - label=ready-to-merge
      - label=v/5.5
