---
merge_queue:
  max_parallel_checks: 1
  reset_on_external_merge: never

queue_rules:
  - name: default
    batch_size: 1
    queue_conditions:
      - label=ready-to-merge
      - '#approved-reviews-by>=1'
    merge_conditions:
      - label=ready-to-merge
      - '#approved-reviews-by>=1'
      - status-success~=^check-author-signed-cla
      - status-success=ci/jenkins/pr_tests
      - status-success~=^Test CrateDB SQL on ubuntu
      - status-success=docs/readthedocs.org:crate
      - status-success~=^checkstyle
      - status-success~=^forbiddenApis
      - status-success~=^Vale
    merge_method: rebase

pull_request_rules:
  - name: default
    conditions: []
    actions:
      queue:

  - name: backport 6.0
    actions:
      backport:
        ignore_conflicts: true
        branches:
          - '6.0'
    conditions:
      - label=ready-to-merge
      - label=v/6.0

  - name: backport 5.10
    actions:
      backport:
        ignore_conflicts: true
        branches:
          - '5.10'
    conditions:
      - label=ready-to-merge
      - label=v/5.10

  - name: backport 5.9
    actions:
      backport:
        ignore_conflicts: true
        branches:
          - '5.9'
    conditions:
      - label=ready-to-merge
      - label=v/5.9
