---
queue_rules:
  - name: default
    conditions:
      - check-success=ci/jenkins/pr_tests
      - check-success~=^Test CrateDB SQL on ubuntu
      - check-success~=^Test CrateDB SQL on windows
      - check-success=docs/readthedocs.org:crate
      - check-success~=^checkstyle
      - check-success~=^Vale


pull_request_rules:
  - name: automatic merge
    conditions:
      - label=ready-to-merge
      - '#approved-reviews-by>=1'
      - status-success=ci/jenkins/pr_tests
      - status-success~=^Test CrateDB SQL on ubuntu
      - status-success~=^Test CrateDB SQL on windows
      - status-success=docs/readthedocs.org:crate
      - status-success~=^checkstyle
      - status-success~=^Vale
    actions:
      queue:
        method: rebase
        name: default
        rebase_fallback: none

  - name: backport 4.7
    actions:
      backport:
        ignore_conflicts: true
        branches:
          - '4.7'
    conditions:
      - label=ready-to-merge
      - label=v/4.7

  - name: backport 4.6
    actions:
      backport:
        ignore_conflicts: true
        branches:
          - '4.6'
    conditions:
      - label=ready-to-merge
      - label=v/4.6

  - name: backport 3.3
    actions:
      backport:
        ignore_conflicts: true
        branches:
          - '3.3'
    conditions:
      - label=ready-to-merge
      - label=v/3.3
