---
pull_request_rules:
  - actions:
      merge:
        method: rebase
        rebase_fallback: null
        strict: true
    conditions:
      - label=ready-to-merge
      - '#approved-reviews-by>=1'
      - status-success=ci/jenkins/pr_tests
      - status-success~=^Test CrateDB SQL on ubuntu
      - status-success~=^Test CrateDB SQL on windows
      - status-success=docs/readthedocs.org:crate
      - status-success~=^CrateDB SQL / checkstyle
    name: default
  - actions:
      backport:
        ignore_conflicts: true
        branches:
          - '4.6'
    conditions:
      - label=ready-to-merge
      - label=v/4.6
    name: backport 4.6
  - actions:
      backport:
        ignore_conflicts: true
        branches:
          - '4.5'
    conditions:
      - label=ready-to-merge
      - label=v/4.5
    name: backport 4.5
  - actions:
      backport:
        ignore_conflicts: true
        branches:
          - '3.3'
    conditions:
      - label=ready-to-merge
      - label=v/3.3
    name: backport 3.3
