# RTD configuration using the `uv` package and project manager.
# https://docs.readthedocs.io/en/stable/build-customization.html#install-dependencies-with-uv
---
version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.13"

  jobs:

    # Install dependencies using `uv`.
    create_environment:
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
      - uv venv
    install:
      - uv pip install -r docs/requirements.txt

    # Invoke the build using `uv`.
    build:
      html:
        - uv run sphinx-build -T -b html docs $READTHEDOCS_OUTPUT/html

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true
