# The Chart for a crateDB deployment with working defaults consists of:
#   1) A Service (exposing the ports that crate uses)
#   2) A StatefulSet (initialising the cluster)
#   3) Resources definition
app: crate

image:
  tag: 4.0.3

# 1) The Service connecting 3 ports.
service:
  name: crate
  type: ClusterIP
  ports:
    psql: 5432
    ui: 4200

# 2) The StatefulSet forming the cluster. Read more:
# https://crate.io/docs/crate/guide/en/latest/scaling/multi-node-setup.html#id10
# https://crate.io/docs/crate/reference/en/latest/config/environment.html#use-max-50-of-available-ram
crate:
  clusterName: my-cluster
  crateHeapSize: 1g
  recoverAfterNodes: 1
  numberOfNodes: 1  # If you want more replicas, checkout the links above.

http:
  cors:
    enabled: false
    allowOrigin: "*"

# 3) Resources and Volumes.
resources:
  requests:
    memory: 1Gi
  limits:
    memory: 2Gi

persistentVolume:
  enabled: true
  storageClass: retain
  accessModes:
    - ReadWriteOnce
  size: 10Gi  # Per instance
  annotations: {}
