
CREATE TABLE IF NOT EXISTS RUNS
(
    ID          INT     AUTO_INCREMENT  PRIMARY KEY,

    TSTAMP      TIMESTAMP NOT NULL DEFAULT NOW(),

    JVM         VARCHAR(500),
    OS          VARCHAR(500)
);
