
CREATE TABLE IF NOT EXISTS TESTS
(
    ID          INT AUTO_INCREMENT PRIMARY KEY,

    RUN_ID      INT REFERENCES RUNS(ID),

    CLASSNAME   VARCHAR(500) NOT NULL,
    NAME        VARCHAR(500) NOT NULL,

    BENCHMARK_ROUNDS INT NOT NULL,
    WARMUP_ROUNDS    INT NOT NULL,
    
    ROUND_AVG        DOUBLE NOT NULL,
    ROUND_STDDEV     DOUBLE NOT NULL,

    GC_AVG        DOUBLE NOT NULL,
    GC_STDDEV     DOUBLE NOT NULL,

    GC_INVOCATIONS    INT NOT NULL,
    GC_TIME       DOUBLE NOT NULL,

    TIME_BENCHMARK       DOUBLE NOT NULL,
    TIME_WARMUP     DOUBLE NOT NULL
);
