rootLogger: INFO, console

logger:
  action: DEBUG
  io.crate.action.sql: DEBUG

appender:
  console:
    type: console
    layout:
      type: consolePattern
      conversionPattern: "[%d{ISO8601}][%-5p][%-25c] %m%n"
