CREATE TABLE t1 (
col1 INTEGER UNSIGNED NOT NULL,
col2 INTEGER UNSIGNED,
col3 smallint UNSIGNED NOT NULL, 
col4 smallint UNSIGNED,
col5 bigint UNSIGNED NOT NULL, 
col6 bigint UNSIGNED,

col20 FLOAT UNSIGNED NOT NULL, 
col21 FLOAT UNSIGNED,
col22 REAL UNSIGNED NOT NULL,
col23 REAL UNSIGNED,
col24 DOUBLE UNSIGNED NOT NULL, 
col25 DOUBLE UNSIGNED, 

col50 DECIMAL UNSIGNED NOT NULL, 
col51 DECIMAL UNSIGNED, 
col52 DECIMAL (1) UNSIGNED NOT NULL, 
col53 DECIMAL (1) UNSIGNED,
col54 DECIMAL (10) UNSIGNED NOT NULL,
col55 DECIMAL (10) UNSIGNED,
col56 DECIMAL (1,1) UNSIGNED NOT NULL,
col57 DECIMAL (1,1) UNSIGNED,
col58 DECIMAL (10,1) UNSIGNED NOT NULL,
col59 DECIMAL (10,1) UNSIGNED,
col60 DECIMAL (10,10) UNSIGNED NOT NULL,
col61 DECIMAL (10,10) UNSIGNED,
col62 DECIMAL (30,10) UNSIGNED NOT NULL,
col63 DECIMAL (30,10) UNSIGNED,

col70 NUMERIC UNSIGNED NOT NULL,
col71 NUMERIC UNSIGNED 
)