apiVersion: "apps/v1"
kind: StatefulSet
metadata:
  name: crate
spec:
  serviceName: "crate-db"
  replicas: {{ .Values.crate.numberOfNodes }}
  selector:
    matchLabels:
      app: {{ .Values.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
        app.kubernetes.io/name: crate-deployment
        app.kubernetes.io/part-of: crate-db
        app.kubernetes.io/version: {{ .Values.image.tag }}
        app.kubernetes.io/managed-by: helm
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      containers:
      - name: crate
        image: crate:{{ .Values.image.tag }}
        imagePullPolicy: IfNotPresent
        command:
          - /docker-entrypoint.sh
          - -Clicense.enterprise=false
          - -Ccluster.name={{ .Values.crate.clusterName }}
          - -Cnetwork.host="0.0.0.0"
          - -Cdiscovery.seed_providers=srv
          - -Cdiscovery.srv.query=_{{ .Values.service.clusterName }}._tcp.{{ .Values.service.name }}.{{ .Release.Namespace }}.svc.cluster.local
          - -Cgateway.recover_after_nodes={{ .Values.crate.recoverAfterNodes }}
          - -Cgateway.expected_nodes={{ .Values.crate.numberOfNodes }}
          - -Chttp.cors.enabled={{ .Values.http.cors.enabled }}
          - -Chttp.cors.allow-origin={{ .Values.http.cors.allowOrigin }}
          - -Cpath.data=/data
          {{- if .Values.resources.limits.cpu }}
          - -Cprocessors={{ .Values.resources.limits.cpu }}
          {{- end }}
        volumeMounts:
            - mountPath: /data
              name: data
        resources:
{{ toYaml .Values.resources | indent 10 }}
        ports:
        - containerPort: {{ .Values.service.ports.psql }}
          name: psql
        - containerPort: 4300
          name: transport
        - containerPort: {{ .Values.service.ports.ui }}
          name: ui
        env:
        - name: CRATE_HEAP_SIZE
          value: {{ .Values.crate.crateHeapSize | quote }}
        - name: CLUSTER_NAME
          value: {{ .Values.crate.clusterName | quote }}
        - name: RECOVER_AFTER_NODES
          value: {{ .Values.crate.recoverAfterNodes | quote }}
        livenessProbe:
          exec:
            command: ["sh", "-c", "curl http://localhost:4200 2&>/dev/null | grep '\"ok\" : true'"]
          initialDelaySeconds: 100
          periodSeconds: 60
{{- if .Values.persistentVolume.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
        annotations:
        {{- range $key, $value := .Values.persistentVolume.annotations }}
          {{ $key }}: {{ $value }}
        {{- end }}
      spec:
        accessModes:
        {{- range .Values.persistentVolume.accessModes }}
          - {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistentVolume.size | quote }}
      {{- if .Values.persistentVolume.storageClass }}
        storageClassName: "{{ .Values.persistentVolume.storageClass }}"
      {{- end }}
{{- else }}
        - name: data
          emptyDir:
            medium: "Memory"
{{- end }}
