/*
 * Licensed to Crate.io GmbH ("Crate") under one or more contributor
 * license agreements.  See the NOTICE file distributed with this work for
 * additional information regarding copyright ownership.  Crate licenses
 * this file to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.  You may
 * obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations
 * under the License.
 *
 * However, if you have executed another commercial license agreement
 * with Crate these terms will supersede the license and you may use the
 * software solely pursuant to the terms of the relevant commercial agreement.
 */

package io.crate.execution.engine.collect;

import java.util.ArrayList;
import java.util.List;
import java.util.function.Function;

import org.elasticsearch.index.translog.Translog;
import org.jspecify.annotations.Nullable;

import io.crate.analyze.Id;
import io.crate.common.annotations.NotThreadSafe;
import io.crate.data.Input;
import io.crate.data.Row;
import io.crate.expression.InputFactory;
import io.crate.expression.symbol.Symbol;
import io.crate.metadata.ColumnIdent;
import io.crate.metadata.NodeContext;
import io.crate.metadata.TransactionContext;
import io.crate.metadata.doc.SysColumns;
import io.crate.types.DataTypes;

@NotThreadSafe
public class RowShardResolver {

    private final Function<List<String>, String> idFunction;
    private final List<Input<?>> primaryKeyInputs;
    private final Input<?> routingInput;
    private final Iterable<CollectExpression<Row, ?>> expressions;

    private String id;
    private String routing;
    private List<String> pkValues;
    private long autoGeneratedTimestamp = Translog.UNSET_AUTO_GENERATED_TIMESTAMP;
    private boolean setAutoGeneratedTimestamp;


    public RowShardResolver(TransactionContext txnCtx,
                            NodeContext nodeCtx,
                            List<ColumnIdent> pkColumns,
                            List<? extends Symbol> primaryKeySymbols,
                            @Nullable ColumnIdent clusteredByColumn,
                            @Nullable Symbol routingSymbol) {
        InputFactory inputFactory = new InputFactory(nodeCtx);
        InputFactory.Context<CollectExpression<Row, ?>> context = inputFactory.ctxForInputColumns(txnCtx);
        idFunction = Id.compileWithNullValidation(pkColumns, clusteredByColumn);
        setAutoGeneratedTimestamp = pkColumns.isEmpty() || (pkColumns.size() == 1 && pkColumns.get(0).equals(SysColumns.ID.COLUMN));
        primaryKeyInputs = new ArrayList<>(primaryKeySymbols.size());
        for (Symbol primaryKeySymbol : primaryKeySymbols) {
            primaryKeyInputs.add(context.add(primaryKeySymbol));
        }
        if (routingSymbol == null) {
            routingInput = null;
        } else {
            int idx = primaryKeySymbols.indexOf(routingSymbol);
            if (idx == -1) {
                routingInput = context.add(routingSymbol);
            } else {
                routingInput = primaryKeyInputs.get(idx);
            }
        }
        expressions = context.expressions();
    }


    public void setNextRow(Row row) {
        for (CollectExpression<Row, ?> expression : expressions) {
            expression.setNextRow(row);
        }
        if (setAutoGeneratedTimestamp) {
            autoGeneratedTimestamp = Math.max(0, System.currentTimeMillis());
        }
        ArrayList<Object> rawPkValues = new ArrayList<>(primaryKeyInputs.size());
        for (var pkInput : primaryKeyInputs) {
            rawPkValues.add(pkInput.value());
        }
        if (routingInput == null) {
            routing = null;
        } else {
            // Reuse value from primaryKeyInput if clustered by is part of primary key columns
            // to avoid duplicate evaluation in case of undeterministic functions (e.g. default uuid)
            int pkIdx = primaryKeyInputs.indexOf(routingInput);
            if (pkIdx > -1) {
                Object value = rawPkValues.get(pkIdx);
                // `id` value is created using StringType.implicitCast
                // `routing` value is created using value.toString()
                // This can lead to different values. E.g. bool `t` vs `true`
                routing = value == null ? null : value.toString();
            } else {
                // If clustered by column is specified it cannot be null.
                var clusteredBy = routingInput.value();
                if (clusteredBy == null) {
                    throw new IllegalArgumentException("Clustered by value must not be NULL");
                }
                routing = clusteredBy.toString();
            }
        }
        pkValues = mutateToStringValues(rawPkValues);
        id = idFunction.apply(pkValues);
    }


    @SuppressWarnings({ "unchecked", "rawtypes" })
    private static List<String> mutateToStringValues(List<Object> rawPkValues) {
        for (int i = 0; i < rawPkValues.size(); i++) {
            rawPkValues.set(i, DataTypes.STRING.implicitCast(rawPkValues.get(i)));
        }
        return (List<String>)(List) rawPkValues;
    }

    public long autoGeneratedTimestamp() {
        return autoGeneratedTimestamp;
    }

    public List<String> pkValues() {
        return pkValues;
    }

    /**
     * Returns the through collected inputs generated id
     */
    public String id() {
        return id;
    }

    /**
     * Returns the collected routing value (if available)
     */
    @Nullable
    public String routing() {
        return routing;
    }
}
