/*
 * Licensed to Crate under one or more contributor license agreements.
 * See the NOTICE file distributed with this work for additional
 * information regarding copyright ownership.  Crate licenses this file
 * to you under the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License.  You may
 * obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
 * implied.  See the License for the specific language governing
 * permissions and limitations under the License.
 *
 * However, if you have executed another commercial license agreement
 * with Crate these terms will supersede the license and you may use the
 * software solely pursuant to the terms of the relevant commercial
 * agreement.
 */

package io.crate.protocols.postgres.types;

public enum PGErrorCodes {

   SUCCESSFUL_COMPLETION("00000", 'S', "successful_completion"),
   WARNING("01000", 'W', "warning"),
   WARNING_DYNAMIC_RESULT_SETS_RETURNED("0100C", 'W', "dynamic_result_sets_returned"),
   WARNING_IMPLICIT_ZERO_BIT_PADDING("01008", 'W', "implicit_zero_bit_padding"),
   WARNING_NULL_VALUE_ELIMINATED_IN_SET_FUNCTION("01003", 'W', "null_value_eliminated_in_set_function"),
   WARNING_PRIVILEGE_NOT_GRANTED("01007", 'W', "privilege_not_granted"),
   WARNING_PRIVILEGE_NOT_REVOKED("01006", 'W', "privilege_not_revoked"),
   WARNING_STRING_DATA_RIGHT_TRUNCATION("01004", 'W', "string_data_right_truncation"),
   WARNING_DEPRECATED_FEATURE("01P01", 'W', "deprecated_feature"),
   NO_DATA("02000", 'W', "no_data"),
   NO_ADDITIONAL_DYNAMIC_RESULT_SETS_RETURNED("02001", 'W', "no_additional_dynamic_result_sets_returned"),
   SQL_STATEMENT_NOT_YET_COMPLETE("03000", 'E', "sql_statement_not_yet_complete"),
   CONNECTION_EXCEPTION("08000", 'E', "connection_exception"),
   CONNECTION_DOES_NOT_EXIST("08003", 'E', "connection_does_not_exist"),
   CONNECTION_FAILURE("08006", 'E', "connection_failure"),
   SQLCLIENT_UNABLE_TO_ESTABLISH_SQLCONNECTION("08001", 'E', "sqlclient_unable_to_establish_sqlconnection"),
   SQLSERVER_REJECTED_ESTABLISHMENT_OF_SQLCONNECTION("08004", 'E', "sqlserver_rejected_establishment_of_sqlconnection"),
   TRANSACTION_RESOLUTION_UNKNOWN("08007", 'E', "transaction_resolution_unknown"),
   PROTOCOL_VIOLATION("08P01", 'E', "protocol_violation"),
   TRIGGERED_ACTION_EXCEPTION("09000", 'E', "triggered_action_exception"),
   FEATURE_NOT_SUPPORTED("0A000", 'E', "feature_not_supported"),
   INVALID_TRANSACTION_INITIATION("0B000", 'E', "invalid_transaction_initiation"),
   LOCATOR_EXCEPTION("0F000", 'E', "locator_exception"),
   L_E_INVALID_SPECIFICATION("0F001", 'E', "invalid_locator_specification"),
   INVALID_GRANTOR("0L000", 'E', "invalid_grantor"),
   INVALID_GRANT_OPERATION("0LP01", 'E', "invalid_grant_operation"),
   INVALID_ROLE_SPECIFICATION("0P000", 'E', "invalid_role_specification"),
   DIAGNOSTICS_EXCEPTION("0Z000", 'E', "diagnostics_exception"),
   STACKED_DIAGNOSTICS_ACCESSED_WITHOUT_ACTIVE_HANDLER("0Z002", 'E', "stacked_diagnostics_accessed_without_active_handler"),
   CASE_NOT_FOUND("20000", 'E', "case_not_found"),
   CARDINALITY_VIOLATION("21000", 'E', "cardinality_violation"),
   DATA_EXCEPTION("22000", 'E', "data_exception"),
   ARRAY_ELEMENT_ERROR("2202E", 'E', ""),
   ARRAY_SUBSCRIPT_ERROR("2202E", 'E', "array_subscript_error"),
   CHARACTER_NOT_IN_REPERTOIRE("22021", 'E', "character_not_in_repertoire"),
   DATETIME_FIELD_OVERFLOW("22008", 'E', "datetime_field_overflow"),
   DATETIME_VALUE_OUT_OF_RANGE("22008", 'E', ""),
   DIVISION_BY_ZERO("22012", 'E', "division_by_zero"),
   ERROR_IN_ASSIGNMENT("22005", 'E', "error_in_assignment"),
   ESCAPE_CHARACTER_CONFLICT("2200B", 'E', "escape_character_conflict"),
   INDICATOR_OVERFLOW("22022", 'E', "indicator_overflow"),
   INTERVAL_FIELD_OVERFLOW("22015", 'E', "interval_field_overflow"),
   INVALID_ARGUMENT_FOR_LOG("2201E", 'E', "invalid_argument_for_logarithm"),
   INVALID_ARGUMENT_FOR_NTILE("22014", 'E', "invalid_argument_for_ntile_function"),
   INVALID_ARGUMENT_FOR_NTH_VALUE("22016", 'E', "invalid_argument_for_nth_value_function"),
   INVALID_ARGUMENT_FOR_POWER_FUNCTION("2201F", 'E', "invalid_argument_for_power_function"),
   INVALID_ARGUMENT_FOR_WIDTH_BUCKET_FUNCTION("2201G", 'E', "invalid_argument_for_width_bucket_function"),
   INVALID_CHARACTER_VALUE_FOR_CAST("22018", 'E', "invalid_character_value_for_cast"),
   INVALID_DATETIME_FORMAT("22007", 'E', "invalid_datetime_format"),
   INVALID_ESCAPE_CHARACTER("22019", 'E', "invalid_escape_character"),
   INVALID_ESCAPE_OCTET("2200D", 'E', "invalid_escape_octet"),
   INVALID_ESCAPE_SEQUENCE("22025", 'E', "invalid_escape_sequence"),
   NONSTANDARD_USE_OF_ESCAPE_CHARACTER("22P06", 'E', "nonstandard_use_of_escape_character"),
   INVALID_INDICATOR_PARAMETER_VALUE("22010", 'E', "invalid_indicator_parameter_value"),
   INVALID_PARAMETER_VALUE("22023", 'E', "invalid_parameter_value"),
   INVALID_PRECEDING_OR_FOLLOWING_SIZE("22013", 'E', "invalid_preceding_or_following_size"),
   INVALID_REGULAR_EXPRESSION("2201B", 'E', "invalid_regular_expression"),
   INVALID_ROW_COUNT_IN_LIMIT_CLAUSE("2201W", 'E', "invalid_row_count_in_limit_clause"),
   INVALID_ROW_COUNT_IN_RESULT_OFFSET_CLAUSE("2201X", 'E', "invalid_row_count_in_result_offset_clause"),
   INVALID_TABLESAMPLE_ARGUMENT("2202H", 'E', "invalid_tablesample_argument"),
   INVALID_TABLESAMPLE_REPEAT("2202G", 'E', "invalid_tablesample_repeat"),
   INVALID_TIME_ZONE_DISPLACEMENT_VALUE("22009", 'E', "invalid_time_zone_displacement_value"),
   INVALID_USE_OF_ESCAPE_CHARACTER("2200C", 'E', "invalid_use_of_escape_character"),
   MOST_SPECIFIC_TYPE_MISMATCH("2200G", 'E', "most_specific_type_mismatch"),
   NULL_VALUE_NOT_ALLOWED("22004", 'E', "null_value_not_allowed"),
   NULL_VALUE_NO_INDICATOR_PARAMETER("22002", 'E', "null_value_no_indicator_parameter"),
   NUMERIC_VALUE_OUT_OF_RANGE("22003", 'E', "numeric_value_out_of_range"),
   SEQUENCE_GENERATOR_LIMIT_EXCEEDED("2200H", 'E', "sequence_generator_limit_exceeded"),
   STRING_DATA_LENGTH_MISMATCH("22026", 'E', "string_data_length_mismatch"),
   STRING_DATA_RIGHT_TRUNCATION("22001", 'E', "string_data_right_truncation"),
   SUBSTRING_ERROR("22011", 'E', "substring_error"),
   TRIM_ERROR("22027", 'E', "trim_error"),
   UNTERMINATED_C_STRING("22024", 'E', "unterminated_c_string"),
   ZERO_LENGTH_CHARACTER_STRING("2200F", 'E', "zero_length_character_string"),
   FLOATING_POINT_EXCEPTION("22P01", 'E', "floating_point_exception"),
   INVALID_TEXT_REPRESENTATION("22P02", 'E', "invalid_text_representation"),
   INVALID_BINARY_REPRESENTATION("22P03", 'E', "invalid_binary_representation"),
   BAD_COPY_FILE_FORMAT("22P04", 'E', "bad_copy_file_format"),
   UNTRANSLATABLE_CHARACTER("22P05", 'E', "untranslatable_character"),
   NOT_AN_XML_DOCUMENT("2200L", 'E', "not_an_xml_document"),
   INVALID_XML_DOCUMENT("2200M", 'E', "invalid_xml_document"),
   INVALID_XML_CONTENT("2200N", 'E', "invalid_xml_content"),
   INVALID_XML_COMMENT("2200S", 'E', "invalid_xml_comment"),
   INVALID_XML_PROCESSING_INSTRUCTION("2200T", 'E', "invalid_xml_processing_instruction"),
   DUPLICATE_JSON_OBJECT_KEY_VALUE("22030", 'E', "duplicate_json_object_key_value"),
   INVALID_JSON_TEXT("22032", 'E', "invalid_json_text"),
   INVALID_JSON_SUBSCRIPT("22033", 'E', "invalid_json_subscript"),
   MORE_THAN_ONE_JSON_ITEM("22034", 'E', "more_than_one_json_item"),
   NO_JSON_ITEM("22035", 'E', "no_json_item"),
   NON_NUMERIC_JSON_ITEM("22036", 'E', "non_numeric_json_item"),
   NON_UNIQUE_KEYS_IN_JSON_OBJECT("22037", 'E', "non_unique_keys_in_json_object"),
   SINGLETON_JSON_ITEM_REQUIRED("22038", 'E', "singleton_json_item_required"),
   JSON_ARRAY_NOT_FOUND("22039", 'E', "json_array_not_found"),
   JSON_MEMBER_NOT_FOUND("2203A", 'E', "json_member_not_found"),
   JSON_NUMBER_NOT_FOUND("2203B", 'E', "json_number_not_found"),
   JSON_OBJECT_NOT_FOUND("2203C", 'E', "object_not_found"),
   JSON_SCALAR_REQUIRED("2203F", 'E', "json_scalar_required"),
   TOO_MANY_JSON_ARRAY_ELEMENTS("2203D", 'E', "too_many_json_array_elements"),
   TOO_MANY_JSON_OBJECT_MEMBERS("2203E", 'E', "too_many_json_object_members"),
   INTEGRITY_CONSTRAINT_VIOLATION("23000", 'E', "integrity_constraint_violation"),
   RESTRICT_VIOLATION("23001", 'E', "restrict_violation"),
   NOT_NULL_VIOLATION("23502", 'E', "not_null_violation"),
   FOREIGN_KEY_VIOLATION("23503", 'E', "foreign_key_violation"),
   UNIQUE_VIOLATION("23505", 'E', "unique_violation"),
   CHECK_VIOLATION("23514", 'E', "check_violation"),
   EXCLUSION_VIOLATION("23P01", 'E', "exclusion_violation"),
   INVALID_CURSOR_STATE("24000", 'E', "invalid_cursor_state"),
   INVALID_TRANSACTION_STATE("25000", 'E', "invalid_transaction_state"),
   ACTIVE_SQL_TRANSACTION("25001", 'E', "active_sql_transaction"),
   BRANCH_TRANSACTION_ALREADY_ACTIVE("25002", 'E', "branch_transaction_already_active"),
   HELD_CURSOR_REQUIRES_SAME_ISOLATION_LEVEL("25008", 'E', "held_cursor_requires_same_isolation_level"),
   INAPPROPRIATE_ACCESS_MODE_FOR_BRANCH_TRANSACTION("25003", 'E', "inappropriate_access_mode_for_branch_transaction"),
   INAPPROPRIATE_ISOLATION_LEVEL_FOR_BRANCH_TRANSACTION("25004", 'E', "inappropriate_isolation_level_for_branch_transaction"),
   NO_ACTIVE_SQL_TRANSACTION_FOR_BRANCH_TRANSACTION("25005", 'E', "no_active_sql_transaction_for_branch_transaction"),
   READ_ONLY_SQL_TRANSACTION("25006", 'E', "read_only_sql_transaction"),
   SCHEMA_AND_DATA_STATEMENT_MIXING_NOT_SUPPORTED("25007", 'E', "schema_and_data_statement_mixing_not_supported"),
   NO_ACTIVE_SQL_TRANSACTION("25P01", 'E', "no_active_sql_transaction"),
   IN_FAILED_SQL_TRANSACTION("25P02", 'E', "in_failed_sql_transaction"),
   IDLE_IN_TRANSACTION_SESSION_TIMEOUT("25P03", 'E', "idle_in_transaction_session_timeout"),
   INVALID_SQL_STATEMENT_NAME("26000", 'E', "invalid_sql_statement_name"),
   TRIGGERED_DATA_CHANGE_VIOLATION("27000", 'E', "triggered_data_change_violation"),
   INVALID_AUTHORIZATION_SPECIFICATION("28000", 'E', "invalid_authorization_specification"),
   INVALID_PASSWORD("28P01", 'E', "invalid_password"),
   DEPENDENT_PRIVILEGE_DESCRIPTORS_STILL_EXIST("2B000", 'E', "dependent_privilege_descriptors_still_exist"),
   DEPENDENT_OBJECTS_STILL_EXIST("2BP01", 'E', "dependent_objects_still_exist"),
   INVALID_TRANSACTION_TERMINATION("2D000", 'E', "invalid_transaction_termination"),
   SQL_ROUTINE_EXCEPTION("2F000", 'E', "sql_routine_exception"),
   S_R_E_FUNCTION_EXECUTED_NO_RETURN_STATEMENT("2F005", 'E', "function_executed_no_return_statement"),
   S_R_E_MODIFYING_SQL_DATA_NOT_PERMITTED("2F002", 'E', "modifying_sql_data_not_permitted"),
   S_R_E_PROHIBITED_SQL_STATEMENT_ATTEMPTED("2F003", 'E', "prohibited_sql_statement_attempted"),
   S_R_E_READING_SQL_DATA_NOT_PERMITTED("2F004", 'E', "reading_sql_data_not_permitted"),
   INVALID_CURSOR_NAME("34000", 'E', "invalid_cursor_name"),
   EXTERNAL_ROUTINE_EXCEPTION("38000", 'E', "external_routine_exception"),
   E_R_E_CONTAINING_SQL_NOT_PERMITTED("38001", 'E', "containing_sql_not_permitted"),
   E_R_E_MODIFYING_SQL_DATA_NOT_PERMITTED("38002", 'E', "modifying_sql_data_not_permitted"),
   E_R_E_PROHIBITED_SQL_STATEMENT_ATTEMPTED("38003", 'E', "prohibited_sql_statement_attempted"),
   E_R_E_READING_SQL_DATA_NOT_PERMITTED("38004", 'E', "reading_sql_data_not_permitted"),
   EXTERNAL_ROUTINE_INVOCATION_EXCEPTION("39000", 'E', "external_routine_invocation_exception"),
   E_R_I_E_INVALID_SQLSTATE_RETURNED("39001", 'E', "invalid_sqlstate_returned"),
   E_R_I_E_NULL_VALUE_NOT_ALLOWED("39004", 'E', "null_value_not_allowed"),
   E_R_I_E_TRIGGER_PROTOCOL_VIOLATED("39P01", 'E', "trigger_protocol_violated"),
   E_R_I_E_SRF_PROTOCOL_VIOLATED("39P02", 'E', "srf_protocol_violated"),
   E_R_I_E_EVENT_TRIGGER_PROTOCOL_VIOLATED("39P03", 'E', "event_trigger_protocol_violated"),
   SAVEPOINT_EXCEPTION("3B000", 'E', "savepoint_exception"),
   S_E_INVALID_SPECIFICATION("3B001", 'E', "invalid_savepoint_specification"),
   INVALID_CATALOG_NAME("3D000", 'E', "invalid_catalog_name"),
   INVALID_SCHEMA_NAME("3F000", 'E', "invalid_schema_name"),
   TRANSACTION_ROLLBACK("40000", 'E', "transaction_rollback"),
   T_R_INTEGRITY_CONSTRAINT_VIOLATION("40002", 'E', "transaction_integrity_constraint_violation"),
   T_R_SERIALIZATION_FAILURE("40001", 'E', "serialization_failure"),
   T_R_STATEMENT_COMPLETION_UNKNOWN("40003", 'E', "statement_completion_unknown"),
   T_R_DEADLOCK_DETECTED("40P01", 'E', "deadlock_detected"),
   SYNTAX_ERROR_OR_ACCESS_RULE_VIOLATION("42000", 'E', "syntax_error_or_access_rule_violation"),
   SYNTAX_ERROR("42601", 'E', "syntax_error"),
   INSUFFICIENT_PRIVILEGE("42501", 'E', "insufficient_privilege"),
   CANNOT_COERCE("42846", 'E', "cannot_coerce"),
   GROUPING_ERROR("42803", 'E', "grouping_error"),
   WINDOWING_ERROR("42P20", 'E', "windowing_error"),
   INVALID_RECURSION("42P19", 'E', "invalid_recursion"),
   INVALID_FOREIGN_KEY("42830", 'E', "invalid_foreign_key"),
   INVALID_NAME("42602", 'E', "invalid_name"),
   NAME_TOO_LONG("42622", 'E', "name_too_long"),
   RESERVED_NAME("42939", 'E', "reserved_name"),
   DATATYPE_MISMATCH("42804", 'E', "datatype_mismatch"),
   INDETERMINATE_DATATYPE("42P18", 'E', "indeterminate_datatype"),
   COLLATION_MISMATCH("42P21", 'E', "collation_mismatch"),
   INDETERMINATE_COLLATION("42P22", 'E', "indeterminate_collation"),
   WRONG_OBJECT_TYPE("42809", 'E', "wrong_object_type"),
   GENERATED_ALWAYS("428C9", 'E', "generated_always"),
   UNDEFINED_COLUMN("42703", 'E', "undefined_column"),
   UNDEFINED_CURSOR("34000", 'E', ""),
   UNDEFINED_DATABASE("3D000", 'E', ""),
   UNDEFINED_FUNCTION("42883", 'E', "undefined_function"),
   UNDEFINED_PSTATEMENT("26000", 'E', ""),
   UNDEFINED_SCHEMA("3F000", 'E', ""),
   UNDEFINED_TABLE("42P01", 'E', "undefined_table"),
   UNDEFINED_PARAMETER("42P02", 'E', "undefined_parameter"),
   UNDEFINED_OBJECT("42704", 'E', "undefined_object"),
   DUPLICATE_COLUMN("42701", 'E', "duplicate_column"),
   DUPLICATE_CURSOR("42P03", 'E', "duplicate_cursor"),
   DUPLICATE_DATABASE("42P04", 'E', "duplicate_database"),
   DUPLICATE_FUNCTION("42723", 'E', "duplicate_function"),
   DUPLICATE_PSTATEMENT("42P05", 'E', "duplicate_prepared_statement"),
   DUPLICATE_SCHEMA("42P06", 'E', "duplicate_schema"),
   DUPLICATE_TABLE("42P07", 'E', "duplicate_table"),
   DUPLICATE_ALIAS("42712", 'E', "duplicate_alias"),
   DUPLICATE_OBJECT("42710", 'E', "duplicate_object"),
   AMBIGUOUS_COLUMN("42702", 'E', "ambiguous_column"),
   AMBIGUOUS_FUNCTION("42725", 'E', "ambiguous_function"),
   AMBIGUOUS_PARAMETER("42P08", 'E', "ambiguous_parameter"),
   AMBIGUOUS_ALIAS("42P09", 'E', "ambiguous_alias"),
   INVALID_COLUMN_REFERENCE("42P10", 'E', "invalid_column_reference"),
   INVALID_COLUMN_DEFINITION("42611", 'E', "invalid_column_definition"),
   INVALID_CURSOR_DEFINITION("42P11", 'E', "invalid_cursor_definition"),
   INVALID_DATABASE_DEFINITION("42P12", 'E', "invalid_database_definition"),
   INVALID_FUNCTION_DEFINITION("42P13", 'E', "invalid_function_definition"),
   INVALID_PSTATEMENT_DEFINITION("42P14", 'E', "invalid_prepared_statement_definition"),
   INVALID_SCHEMA_DEFINITION("42P15", 'E', "invalid_schema_definition"),
   INVALID_TABLE_DEFINITION("42P16", 'E', "invalid_table_definition"),
   INVALID_OBJECT_DEFINITION("42P17", 'E', "invalid_object_definition"),
   WITH_CHECK_OPTION_VIOLATION("44000", 'E', "with_check_option_violation"),
   INSUFFICIENT_RESOURCES("53000", 'E', "insufficient_resources"),
   DISK_FULL("53100", 'E', "disk_full"),
   OUT_OF_MEMORY("53200", 'E', "out_of_memory"),
   TOO_MANY_CONNECTIONS("53300", 'E', "too_many_connections"),
   CONFIGURATION_LIMIT_EXCEEDED("53400", 'E', "configuration_limit_exceeded"),
   PROGRAM_LIMIT_EXCEEDED("54000", 'E', "program_limit_exceeded"),
   STATEMENT_TOO_COMPLEX("54001", 'E', "statement_too_complex"),
   TOO_MANY_COLUMNS("54011", 'E', "too_many_columns"),
   TOO_MANY_ARGUMENTS("54023", 'E', "too_many_arguments"),
   OBJECT_NOT_IN_PREREQUISITE_STATE("55000", 'E', "object_not_in_prerequisite_state"),
   OBJECT_IN_USE("55006", 'E', "object_in_use"),
   CANT_CHANGE_RUNTIME_PARAM("55P02", 'E', "cant_change_runtime_param"),
   LOCK_NOT_AVAILABLE("55P03", 'E', "lock_not_available"),
   UNSAFE_NEW_ENUM_VALUE_USAGE("55P04", 'E', "unsafe_new_enum_value_usage"),
   OPERATOR_INTERVENTION("57000", 'E', "operator_intervention"),
   QUERY_CANCELED("57014", 'E', "query_canceled"),
   ADMIN_SHUTDOWN("57P01", 'E', "admin_shutdown"),
   CRASH_SHUTDOWN("57P02", 'E', "crash_shutdown"),
   CANNOT_CONNECT_NOW("57P03", 'E', "cannot_connect_now"),
   DATABASE_DROPPED("57P04", 'E', "database_dropped"),
   SYSTEM_ERROR("58000", 'E', "system_error"),
   IO_ERROR("58030", 'E', "io_error"),
   UNDEFINED_FILE("58P01", 'E', "undefined_file"),
   DUPLICATE_FILE("58P02", 'E', "duplicate_file"),
   SNAPSHOT_TOO_OLD("72000", 'E', "snapshot_too_old"),
   CONFIG_FILE_ERROR("F0000", 'E', "config_file_error"),
   LOCK_FILE_EXISTS("F0001", 'E', "lock_file_exists"),
   FDW_ERROR("HV000", 'E', "fdw_error"),
   FDW_COLUMN_NAME_NOT_FOUND("HV005", 'E', "fdw_column_name_not_found"),
   FDW_DYNAMIC_PARAMETER_VALUE_NEEDED("HV002", 'E', "fdw_dynamic_parameter_value_needed"),
   FDW_FUNCTION_SEQUENCE_ERROR("HV010", 'E', "fdw_function_sequence_error"),
   FDW_INCONSISTENT_DESCRIPTOR_INFORMATION("HV021", 'E', "fdw_inconsistent_descriptor_information"),
   FDW_INVALID_ATTRIBUTE_VALUE("HV024", 'E', "fdw_invalid_attribute_value"),
   FDW_INVALID_COLUMN_NAME("HV007", 'E', "fdw_invalid_column_name"),
   FDW_INVALID_COLUMN_NUMBER("HV008", 'E', "fdw_invalid_column_number"),
   FDW_INVALID_DATA_TYPE("HV004", 'E', "fdw_invalid_data_type"),
   FDW_INVALID_DATA_TYPE_DESCRIPTORS("HV006", 'E', "fdw_invalid_data_type_descriptors"),
   FDW_INVALID_DESCRIPTOR_FIELD_IDENTIFIER("HV091", 'E', "fdw_invalid_descriptor_field_identifier"),
   FDW_INVALID_HANDLE("HV00B", 'E', "fdw_invalid_handle"),
   FDW_INVALID_OPTION_INDEX("HV00C", 'E', "fdw_invalid_option_index"),
   FDW_INVALID_OPTION_NAME("HV00D", 'E', "fdw_invalid_option_name"),
   FDW_INVALID_STRING_LENGTH_OR_BUFFER_LENGTH("HV090", 'E', "fdw_invalid_string_length_or_buffer_length"),
   FDW_INVALID_STRING_FORMAT("HV00A", 'E', "fdw_invalid_string_format"),
   FDW_INVALID_USE_OF_NULL_POINTER("HV009", 'E', "fdw_invalid_use_of_null_pointer"),
   FDW_TOO_MANY_HANDLES("HV014", 'E', "fdw_too_many_handles"),
   FDW_OUT_OF_MEMORY("HV001", 'E', "fdw_out_of_memory"),
   FDW_NO_SCHEMAS("HV00P", 'E', "fdw_no_schemas"),
   FDW_OPTION_NAME_NOT_FOUND("HV00J", 'E', "fdw_option_name_not_found"),
   FDW_REPLY_HANDLE("HV00K", 'E', "fdw_reply_handle"),
   FDW_SCHEMA_NOT_FOUND("HV00Q", 'E', "fdw_schema_not_found"),
   FDW_TABLE_NOT_FOUND("HV00R", 'E', "fdw_table_not_found"),
   FDW_UNABLE_TO_CREATE_EXECUTION("HV00L", 'E', "fdw_unable_to_create_execution"),
   FDW_UNABLE_TO_CREATE_REPLY("HV00M", 'E', "fdw_unable_to_create_reply"),
   FDW_UNABLE_TO_ESTABLISH_CONNECTION("HV00N", 'E', "fdw_unable_to_establish_connection"),
   PLPGSQL_ERROR("P0000", 'E', "plpgsql_error"),
   RAISE_EXCEPTION("P0001", 'E', "raise_exception"),
   NO_DATA_FOUND("P0002", 'E', "no_data_found"),
   TOO_MANY_ROWS("P0003", 'E', "too_many_rows"),
   ASSERT_FAILURE("P0004", 'E', "assert_failure"),
   INTERNAL_ERROR("XX000", 'E', "internal_error"),
   DATA_CORRUPTED("XX001", 'E', "data_corrupted"),
   INDEX_CORRUPTED("XX002", 'E', "index_corrupted");

    PGErrorCodes(String errorCode, char category, String description) {
       this.errorCode = errorCode;
       this.description = description;
       this.category = category;
    }

    private final String errorCode;
    private final String description;
    private final char category;

    public String errorCode() {
        return errorCode;
    }

    public String description() {
        return description;
    }

    public char category() {
        return category;
    }
}
