---
name: CrateDB Docs
on:
  pull_request:
    paths:
      - '**.rst'
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  checks: write
  statuses: write

jobs:
  vale:
    name: Vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Install docutils
        run: |
          sudo apt-get update
          sudo apt-get install -y docutils

      - name: Run vale
        uses: vale-cli/vale-action@85f9f7f2c5f449ac0ae5b66662961bae3f77ca6a # 2.1.2
        with:
          files: docs/
          version: 3.12.0
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
