---
name: Add PR to CrateDB project board
on:
  pull_request:
    types: [opened, reopened]


jobs:
  automate-project:
    runs-on: ubuntu-latest
    steps:
      - name: Add PR to CrateDB project board
        run: |-
          gh api graphql -F contentId=$PR_ID -f query='
            mutation($contentId: ID!) {
              addProjectV2ItemById(input: {projectId: "PVT_kwDOAD3FaM4ACoUS" contentId: $contentId}) {
                item {
                  id
                }
              }
            }
            '
        env:
          PR_ID: ${{github.event.pull_request.node_id}}
          GITHUB_TOKEN: ${{ secrets.JENKINS_USER_TOKEN }}
